apiVersion: v1
kind: Service
metadata:
  name: sussy-web
spec:
  ports:
  - nodePort: 31532
    port: 4000
    protocol: TCP
    targetPort: 8080
  selector:
    app: sussy-web
  type: LoadBalancer
  externalIPs:
  - 192.168.1.12